In [30]:
import numpy as np
import random

# 실습

In [56]:
x = np.zeros((5,5))
x[1:-1,1:-1] = 1
print(x)
print()
x = np.ones((3,3))
x = np.pad(x, pad_width = 1, mode='constant', constant_values=0)
print(x)
print()
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 실습

In [54]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 실습

In [64]:
data = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
print(data)
print()
batch = data.reshape(2,4,2)
print(batch)

[180  72 172  66 162  60 167  53 176  80 155  60 177  77 130  40]

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


# 실습

In [67]:
def linear_system_solver(ndarr, v):
    # n차 정사각행렬의 역행렬과 상수항 행렬의 행렬곱
    return np.linalg.inv(ndarr).dot(v)

a = np.array([1,1,2,1]).reshape(2,2)
b = np.array([15,25]).reshape(2,1)
print(linear_system_solver(a,b))

[[10.]
 [ 5.]]


# 실습

In [72]:
data = np.random.random((4,6)).round(1)
print(data)
length = np.array([4,1,6,3])
print(length.shape)
length = np.expand_dims(length, 1)
print(length.shape)

[[0.5 0.7 0.9 0.2 0.2 0.5]
 [0.6 0.7 0.9 0.1 0.2 0.3]
 [0.2 0.8 0.7 0.  0.3 0.6]
 [0.9 0.9 0.2 0.8 0.1 0.7]]
(4,)
(4, 1)


In [74]:
maxlen = data.shape[1]
idx = np.arange(maxlen)
idx = np.tile(idx, (4,1))
print(idx)
mask = idx < length
print(mask)
data[~mask] = float('-inf')
print(data)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[ True  True  True  True False False]
 [ True False False False False False]
 [ True  True  True  True  True  True]
 [ True  True  True False False False]]
[[ 0.5  0.7  0.9  0.2 -inf -inf]
 [ 0.6 -inf -inf -inf -inf -inf]
 [ 0.2  0.8  0.7  0.   0.3  0.6]
 [ 0.9  0.9  0.2 -inf -inf -inf]]
